name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'staging'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running in ${{ github.event.inputs.environment }}"
